### ISSUE TITLE
Fails silently when starting a second instance

### ISSUE THREAD

**Issue by escottalexander** [kajoseph/lnd-tools#1]
This happens when you are already running an instance of the server but you attempt to run another with the`lnd-tools serve` command.

It shows several of the usual start up logs but then stops without indicating there was a problem. I wouldn't expect it to run per se but I would expect it to at least give an error.

**Comment by kajoseph** [comment]
Fixed in https://github.com/kajoseph/lnd-tools/commit/1d1334487def48ab3a5f7979995153c265837368

Thanks!
