### ISSUE TITLE
Incorrect array structure returned when whitelist is empty

### ISSUE THREAD

**Issue by escottalexander** [kajoseph/lnd-tools#2]
When there are no public keys whitelisted it returns an incorrect syntax when running `lnd-tools client whitelist list`.

It returns:
```
[
[
]
```
when it should be:
```
[
]
```
The logic on lines 20 and 37 of server/api/routes/channel.js need revising. It *might* only do this after you have added and removed a key.

**Comment by kajoseph** [comment]
Fixed in https://github.com/kajoseph/lnd-tools/commit/6f712aa9fd1e5c7f5dcd4b469563dc7b88fed821

Thanks!
